### ISSUE TITLE
How to organize data to utilize ctc_padding?

### ISSUE THREAD

**Issue by nicedi** [jnishi/ctc-chainer-example#1]
I update my Chainer to 1.7 because the ctc function now support batch training as they said.
I put my input sequences in two dimensional list, but this assertion: "assert blank_symbol < x[0].data.shape[1]" can not pass. I wonder how to organize my data to do mini-batch training. 
I am hungry for your guidance.

**Comment by jnishi** [comment]
The input of connectionist temporal classification must be sequence of two dimensional array. Each element of sequence consists of batch and channels. For example, https://github.com/pfnet/chainer/blob/master/tests/chainer_tests/functions_tests/loss_tests/test_ctc.py#L18 This input is sequence of 4 elements, and each element is 2 dimensional array, which is 2 batches and 3 channels. (This 3 dimensional array is split to sequence of 2 dimensional array here  https://github.com/pfnet/chainer/blob/master/tests/chainer_tests/functions_tests/loss_tests/test_ctc.py#L53 )

"assert blank_symbol < x[0].data.shape[1]" checks if given data of channel has value of ID that is assigned as blank symbol.

**Comment by nicedi** [comment]
Thank you for you detailed explanation. I think I didn't expressed my concern clearly in the last question. Let me re-formulate my question.
In the "[Released v1.7.0](https://groups.google.com/forum/#!topic/chainer/VLdqmWEHlPA)" post posted by Seiya Tokui in the Chainer english forum, he said: "ctc_padding (now minibatch can contain sequences of different lengths, thanks @jnishi!)". I am curious how to organize data to utilize "ctc_padding" to deal with sequences of different lengths. 
I am now using Chainer to train an end-to-end speech recognition model. As you know, the feature sequence (spectragram or mfcc) for each utterance is not the same length. At right now, I train the model with one weight update per utterance. When I found that "minibatch can contain sequences of different lengths" in ctc loss function in Chainer 1.7, I am eager to test it. I tried, but I failed.
I understand the code in https://github.com/pfnet/chainer/blob/master/tests/chainer_tests/functions_tests/loss_tests/test_ctc.py#L53 , however it is still 2 sequences with equal length of 4. So I post my question here to ask for your help.

**Comment by jnishi** [comment]
When you train different length connectionist_temporal_classification, you need to create padded data.
For example, if you have 4 length data and 3 length data, you need to create (2,3) arrays of length 4. And you can put any value in 4th element of 3 length data, because it is ignored if you gives Variable([4,3]) as input_length(, which is argument of connectionist_temporal_classification).  This case is shown in "TestCTCWithInputPadding"' https://github.com/pfnet/chainer/blob/master/tests/chainer_tests/functions_tests/loss_tests/test_ctc.py#L150 . `self.x[3][0]` is ignored because of `self.x_length` (=[3,4]), which is given to connectionist_temporal_classification. 

You need to create padded label data when you train data with different length label. In this case, you need to give length of valid label data via label_length(, which is argument of connectionist_temporal_classification).
You can see this case here. https://github.com/pfnet/chainer/blob/master/tests/chainer_tests/functions_tests/loss_tests/test_ctc.py#L134

**Comment by nicedi** [comment]
Thank you very much, jnishi. I think I should check out "chainer_tests" first in the future if I have any question. Thank you again!

**Comment by jnishi** [comment]
You are welcome.
